<a href="https://colab.research.google.com/github/adalbertii/modele-NLP/blob/main/NLP_with_RNN_case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.14.0'

In [2]:
path_to_file = '/content/drive/MyDrive/dane/shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [6]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [4]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

### Text Vectorization

The neural network can't take in the raw string data.
We need to assign numbers to each character.

Let's create two dictionaries that can go from numeric index to character and character to numeric index.

In [5]:
char_to_ind = {u:i for i, u in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [6]:
ind_to_char = np.array(vocab)
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [7]:
encoded_text = np.array([char_to_ind[c] for c in text])
encoded_text[:100]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64])

In [8]:
encoded_text.shape

(5445609,)

In [9]:
sample = text[:100]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose mi"

In [10]:
encoded_text[:100]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64])

Ogólnie rzecz biorąc, staramy się, aby model przewidywał następną znak o najwyższym prawdopodobieństwie, biorąc pod uwagę historyczną sekwencję znaków. Do nas (użytkownika) należy wybór długości tej historycznej sekwencji. Zbyt krótka sekwencja i nie mamy wystarczających informacji (np. biorąc pod uwagę literę "a", jaki jest następny znak), zbyt długa sekwencja i szkolenie zajmie zbyt dużo czasu i najprawdopodobniej nadmiernie dopasuje się do sekwencji znaków, które są nieistotne dla znaków dalej. Chociaż nie ma prawidłowego wyboru długości sekwencji, należy wziąć pod uwagę sam tekst, jak długie są w nim normalne frazy i rozsądne wyobrażenie o tym, które znaki / słowa są ze sobą powiązane.

In [11]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [12]:
line = "From fairest creatures we desire increase"

In [13]:
len(line)

41

In [14]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

In [15]:
len(part_stanza)

131

### Training Sequences

Rzeczywiste dane tekstowe będą sekwencją tekstową przesuniętą o jeden znak do przodu. Na przykład:

Sequence In: "Hello my name"
Sequence Out: "ello my name"


Możemy użyć funkcji `tf.data.Dataset.from_tensor_slices`, aby przekonwertować wektor tekstowy na strumień indeksów znaków.

In [16]:
seq_len = 120

In [17]:
total_num_seq = len(text)//(seq_len+1)
total_num_seq

45005

In [18]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


Metoda **batch** konwertuje te indywidualne wywołania znaków na sekwencje, które możemy wprowadzić jako batch.
Używamy seq_len+1 z powodu zerowego indeksowania. Oto co oznacza


drop_remainder: (Opcjonalnie.) `tf.bool` skalar `tf.Tensor`, reprezentujący czy ostatnia partia powinna zostać porzucona w przypadku, gdy ma mniej niż  `batch_size` elementów; domyślnym zachowaniem jest nieusuwanie mniejszej batch.
    batch.


In [19]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

Teraz, gdy mamy już nasze sekwencje, wykonamy dla każdej z nich następujące kroki, aby utworzyć docelowe sekwencje tekstowe:

1. podaj sekwencję tekstu wejściowego
2. Przypisz docelową sekwencję tekstu jako sekwencję tekstu wejściowego przesuniętą o jeden krok do przodu
3. Zgrupuj je razem w krotkę

In [20]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [21]:
dataset = sequences.map(create_seq_targets)

In [22]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


### Generowanie  szkoleniowych batch -ów

Teraz, gdy mamy już rzeczywiste sekwencje, utworzymy batch. Chcemy potasować te sekwencje w losowej kolejności, aby model nie pasował do żadnej sekcji tekstu, ale zamiast tego mógł generować znaki na podstawie dowolnego tekstu początkowego.

In [23]:
# Batch size
batch_size = 128

# Rozmiar bufora do przetasowania zbioru danych, tak aby nie próbował on przetasować
# całej sekwencji w pamięci. Zamiast tego utrzymuje bufor, w którym tasuje elementy


buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [24]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

**Utworzenie modelu**

Będziemy używać modelu opartego na LSTM z kilkoma dodatkowymi funkcjami, w tym warstwą osadzającą na początek i **dwoma** warstwami LSTM.

 Architekturę tego modelu oparliśmy na [DeepMoji](https://deepmoji.mit.edu/), a oryginalny kod źródłowy można znaleźć [tutaj](https://github.com/bfelbo/DeepMoji).

Warstwa osadzająca będzie służyć jako warstwa wejściowa, która zasadniczo tworzy tabelę przeglądową, która odwzorowuje indeksy liczbowe każdego znaku na wektor z liczbą wymiarów „embedding dim”. Jak możesz sobie wyobrazić, im większy rozmiar osadzania, tym bardziej złożony jest trening. Jest to podobne do idei stojącej za word2vec, gdzie słowa są odwzorowywane w jakiejś n-wymiarowej przestrzeni. Osadzanie przed przesłaniem bezpośrednio do LSTM zwykle prowadzi do bardziej realistycznych wyników.

In [25]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

### Konfigurowanie funkcji straty

Na naszą stratę użyjemy rzadkiej kategorycznej crossentropii, którą możemy zaimportować z Keras. Ustawimy to również jako logits=True

In [27]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [43]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2

https://datascience.stackexchange.com/questions/41921/sparse-categorical-crossentropy-vs-categorical-crossentropy-keras-accuracy


In [28]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [29]:
# The Gated Recurrent Unit (GRU)
# to rodzaj rekurencyjnej sieci neuronowej (RNN), która w niektórych przypadkach ma przewagę nad pamięcią długoterminową (LSTM).
# GRU zużywa mniej pamięci i jest szybszy niż LSTM,
# jednak LSTM jest dokładniejszy w przypadku korzystania ze zbiorów danych o dłuższych sekwencjach.


def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [30]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


##Trenowanie modelu

Zanim spędzimy zbyt dużo czasu na szkoleniu, upewnijmy się, że wszystko jest w porządku z naszym modelem!

Przekażmy partię, aby potwierdzić, że model obecnie przewiduje losowe znaki bez żadnego szkolenia.

In [32]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")

(128, 120, 84)  <=== (batch_size, sequence_length, vocab_size)


In [33]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 2.0953121e-03,  1.1258886e-02, -2.5940579e-03, ...,
         -1.2392533e-02, -3.4673782e-03, -7.2439230e-04],
        [ 3.2578486e-03,  1.6974702e-02, -3.3724171e-03, ...,
         -1.8630806e-02, -5.6052436e-03, -8.9238683e-04],
        [ 3.2666810e-03,  7.0074308e-03,  8.6849194e-04, ...,
         -9.1478936e-03, -6.6484632e-03, -9.7594662e-03],
        ...,
        [ 4.3208823e-03,  1.6876326e-03, -2.0872334e-03, ...,
          1.0710944e-03, -3.4363889e-03, -1.4540803e-02],
        [ 5.6978567e-03,  1.1195677e-02, -3.8253334e-03, ...,
         -1.1791485e-02, -5.9310542e-03, -8.7070828e-03],
        [ 6.9749728e-03,  1.2424210e-02, -1.0757009e-02, ...,
         -2.5953290e-03,  7.5302966e-04, -2.6490067e-03]],

       [[-1.6526725e-03, -5.7955598e-03, -3.4861043e-03, ...,
          6.0472847e-03,  1.8851823e-03,  8.7492019e-03],
        [ 1.5027629e-03,  6.6816565e-03, -2.8176974e-03, ...,
         -9.6855760e-03, -2

In [34]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [35]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[52],
       [70],
       [46],
       [29],
       [74],
       [18],
       [57],
       [53],
       [76],
       [34],
       [15],
       [ 5],
       [63],
       [56],
       [55],
       [43],
       [70],
       [81],
       [ 0],
       [54],
       [ 8],
       [ 0],
       [ 2],
       [26],
       [15],
       [12],
       [29],
       [46],
       [37],
       [58],
       [18],
       [16],
       [28],
       [32],
       [41],
       [10],
       [71],
       [42],
       [20],
       [68],
       [18],
       [29],
       [22],
       [11],
       [64],
       [ 1],
       [14],
       [ 1],
       [61],
       [54],
       [12],
       [56],
       [ 6],
       [32],
       [ 8],
       [47],
       [44],
       [16],
       [ 4],
       [47],
       [72],
       [ 6],
       [75],
       [25],
       [61],
       [22],
       [12],
       [47],
       [61],
       [25],
       [41],
       [ 0],
       [80],
   

In [36]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [37]:
sampled_indices

array([52, 70, 46, 29, 74, 18, 57, 53, 76, 34, 15,  5, 63, 56, 55, 43, 70,
       81,  0, 54,  8,  0,  2, 26, 15, 12, 29, 46, 37, 58, 18, 16, 28, 32,
       41, 10, 71, 42, 20, 68, 18, 29, 22, 11, 64,  1, 14,  1, 61, 54, 12,
       56,  6, 32,  8, 47, 44, 16,  4, 47, 72,  6, 75, 25, 61, 22, 12, 47,
       61, 25, 41,  0, 80, 23, 81, 10,  8, 33, 56, 16, 59, 60, 14, 50, 30,
       34, 16,  3, 39, 58, 11, 76, 68,  5, 61, 75, 14, 33, 73, 15, 77, 46,
       66, 67, 57, 13, 78, 13, 46, 62, 79, 52, 75, 29, 59, 33, 35, 11, 72,
       24])

In [38]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

  A leg of Rome shall not return to tell
    What crows have peck'd them here. He brags his service,
    As if he were o


Next Char Predictions: 

[oUDs7b]uI4'ha`Roz
_,
!A41DULc75CGP.pQ9m7D;0i 3 f_1a(G,VS5&Vq(t?f;1Vf?P
y<z.,Ha5de3YEI5"Nc0um'ft3Hr4vUklb2w2Ugx[tDdHJ0q>


Po potwierdzeniu, że wymiary działają, przeszkolmy naszą sieć!

In [39]:
epochs = 30

In [40]:
# Procesor T4 GPU - 30 minut
model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 [==============================] - 51s 125ms/step - loss: 2.5313
Epoch 2/30
351/351 [==============================] - 51s 123ms/step - loss: 1.7128
Epoch 3/30
351/351 [==============================] - 47s 125ms/step - loss: 1.4456
Epoch 4/30
351/351 [==============================] - 47s 127ms/step - loss: 1.3306
Epoch 5/30
351/351 [==============================] - 49s 129ms/step - loss: 1.2696
Epoch 6/30
351/351 [==============================] - 46s 125ms/step - loss: 1.2305
Epoch 7/30
351/351 [==============================] - 47s 128ms/step - loss: 1.2019
Epoch 8/30
351/351 [==============================] - 46s 124ms/step - loss: 1.1782
Epoch 9/30
351/351 [==============================] - 47s 128ms/step - loss: 1.1584
Epoch 10/30
351/351 [==============================] - 46s 124ms/step - loss: 1.1418
Epoch 11/30
351/351 [==============================] - 47s 128ms/step - loss: 1.1259
Epoch 12/30
351/351 [==============================] - 46s 124ms/step - lo

## Generowanie tekstu

Obecnie nasz model oczekuje tylko 128 sekwencji na raz. Możemy utworzyć nowy model, który oczekuje tylko rozmiaru partii = 1. Możemy utworzyć nowy model o tej wielkości partii, a następnie załadować zapisane wagi modeli. Następnie wywołaj .build() na modelu:



In [41]:
model.save('/content/drive/MyDrive/dane/modele/shakespeare_gen.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [42]:
from tensorflow.keras.models import load_model

In [64]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('/content/drive/MyDrive/dane/modele/shakespeare_gen.h5')

model.build(tf.TensorShape([1, None]))

In [65]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_3 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_3 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [66]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected

  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [68]:
print(generate_text(model,"From fairest creatures we",gen_size=100))

From fairest creatures well;
    Old Gaunt, sweet Nay, I bid him speak things?
  OLICKA. Would you do it without that neither
