<a href="https://colab.research.google.com/github/adalbertii/modele-NLP/blob/main/Tokenizer_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tokenizer**

Wprowadzenie

In [1]:
from keras.preprocessing.text import Tokenizer

In [2]:
# przykładowy korpus zbioru recenzji
corpus =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]



In [3]:
# Zainicjowanie obiektu klasy Tokenizer i zasilenie obiektu  dokumentami, które będą  analizowane
# parametr "num_words" pozostawiamy domyslny
# zwykle przyjmuje wartośc  = MAX_WORDS
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)


In [4]:
# pobranie indeksów wyrazów dla całego korpusu
word_index = tokenizer.word_index

word_index

{'horrible': 1,
 'food': 2,
 'awesome': 3,
 'never': 4,
 'coming': 5,
 'back': 6,
 'service': 7,
 'rude': 8,
 'waitress': 9,
 'cold': 10,
 'services': 11,
 'rocks': 12,
 'poor': 13,
 'work': 14,
 "couldn't": 15,
 'have': 16,
 'done': 17,
 'better': 18}

In [5]:
# udostępnia słownik słów występujących w dokumentach oraz liczbę dokumentów, w których pojawia się każde słowo.
# dokument tutaj jest rozumiany jako wiersz ze zmiennej "corpus"

word_docs = tokenizer.word_docs

sorted(word_docs.items())

[('awesome', 2),
 ('back', 1),
 ('better', 1),
 ('cold', 1),
 ('coming', 1),
 ("couldn't", 1),
 ('done', 1),
 ('food', 2),
 ('have', 1),
 ('horrible', 2),
 ('never', 1),
 ('poor', 1),
 ('rocks', 1),
 ('rude', 1),
 ('service', 1),
 ('services', 1),
 ('waitress', 1),
 ('work', 1)]

In [6]:
# Pobranie  słownika słów według częstotliwości występowania w korpusie
word_counts = tokenizer.word_counts

sorted(word_counts.items())

[('awesome', 2),
 ('back', 1),
 ('better', 1),
 ('cold', 1),
 ('coming', 1),
 ("couldn't", 1),
 ('done', 1),
 ('food', 2),
 ('have', 1),
 ('horrible', 2),
 ('never', 1),
 ('poor', 1),
 ('rocks', 1),
 ('rude', 1),
 ('service', 1),
 ('services', 1),
 ('waitress', 1),
 ('work', 1)]

In [11]:
import numpy as np
import numpy as np
np.set_printoptions(linewidth=200)    # domyślnie = 75

In [15]:
# Konwertuj teksty na macierz wartości binarnych
binary_matrix = tokenizer.texts_to_matrix(corpus, mode = 'binary')


print(binary_matrix)

# otrzymujemy matrycę 10 wierszową (tyle jest zdań w korpusie)
# omówić reprezentacje zdań z listy źródlowej:
# 'Never coming back!'
# 'poor work'

[[0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]
